on:
  push:
    branches:
      - master

name: 🚀 Deploy using FTP

jobs:
  web-deploy:
    name: 🎉 Running Deployment Process
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'


      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21